In [1]:
import numpy as np

matrix = np.array([(1, 2, 3), (4, 5, 6)])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

### Row Major Iteration

In [2]:
def show_row_major(matrix):
    for row in matrix:
        for col in row:
            print(col)
            
show_row_major(matrix)

1
2
3
4
5
6


### Column Major Iteration

In [3]:
def show_col_major(matrix):
    for col in matrix.T:
        for row in col:
            print(row)
show_col_major(matrix)

1
4
2
5
3
6


### Create Sparse Matrix

In [4]:
sparse = np.array([(1, 0, 5, 0, 0, 0, 0, 9, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 2, 0, 3, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 0, 8, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 0, 0, 0, 9, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 8, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 0, 8, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 0, 0, 0, 9, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 8, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 0, 8, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 0, 0, 0, 9, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 8, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9),
                   (0, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9)])
sparse

array([[1, 0, 5, 0, 0, 0, 0, 9, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 2, 0, 3, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 0, 8, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 9, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0,

### Calculate Total Non Zero Elements (nnz) 

In [5]:
def get_nnz(sparse_matrix):
    nnz = 0
    for i in sparse:
        for j in i:
            if j != 0:
                nnz += 1

    return nnz

get_nnz(sparse)

151

### Calculate Sparsity

In [6]:
def calculate_sparsity(sparse_matrix):
    nnz = get_nnz(sparse_matrix)
    rows, cols = np.shape(sparse)
    return 1 - ( nnz / (rows * cols) )

calculate_sparsity(sparse)

0.7633228840125392

### Calculate Density

In [7]:
def calculate_density(sparse_matrix):
    nnz = get_nnz(sparse_matrix)
    rows, cols = np.shape(sparse)
    return ( nnz / (rows * cols) )

calculate_density(sparse)

0.23667711598746083

### Convert From Sparse Matrix to COO Format
- Storage Complexity = 3nnz
- Compute Complexity = N because it does on iteration over the matrix

In [8]:
def sparse_to_coo(sparse_matrix):
    row_coo = []
    col_coo = []
    val_coo = []
    row_count = np.shape(sparse_matrix)[0]
    col_count = np.shape(sparse_matrix)[1]

    for row_index, row in enumerate(sparse_matrix):
        for col_index, value in enumerate(row):
            if value != 0:
                row_coo.append(row_index)
                col_coo.append(col_index)
                val_coo.append(value)
    return row_coo, col_coo, val_coo, row_count, col_count

row_coo, col_coo, val_coo, row_count, col_count = sparse_to_coo(sparse)

print("row:", row_coo, "\n")
print("col:", col_coo, "\n")
print("val:", val_coo, "\n")
print("row_count:", row_count, "\n")
print("col_count:", col_count, "\n")
print("storage:", len(row_coo) + len(col_coo) + len(val_coo) + 1 + 1, "\n")

row: [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28] 

col: [0, 2, 7, 9, 11, 16, 21, 1, 3, 9, 11, 16, 21, 2, 9, 11, 16, 21, 1, 9, 11, 16, 21, 8, 9, 11, 16, 21, 3, 9, 11, 16, 21, 7, 9, 11, 16, 21, 5, 9, 11, 16, 21, 1, 9, 11, 16, 21, 2, 9, 11, 16, 21, 4, 6, 9, 11, 16, 21, 2, 9, 11, 16, 21, 1, 9, 11, 16, 21, 8, 9, 11, 16, 21, 3, 9, 11, 16, 21, 7, 9, 11, 16, 21, 5, 9, 11, 16, 21, 1, 9, 11, 16, 21, 2, 9, 11, 16, 21, 4, 6, 9, 11, 16, 21, 2, 9, 11, 16, 21, 1, 9, 11, 16, 21, 8, 9, 11, 16, 21, 3, 9, 

### Convert from COO Format to Matrix

In [9]:
def coo_to_matrix(row_coo, col_coo, val_coo, row_count, col_count):
    dense = np.zeros((row_count, col_count), dtype=int)
    for r, c, v in zip(row_coo, col_coo, val_coo):
        dense[r, c] = v
    return dense

coo_result = coo_to_matrix(row_coo, col_coo, val_coo, row_count, col_count)
coo_result

array([[1, 0, 5, 0, 0, 0, 0, 9, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 2, 0, 3, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 0, 8, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 9, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0,

In [19]:
np.testing.assert_equal(coo_result, sparse)

### Convert From Sparse Matrix to CSR Format

In [11]:
def sparse_to_csr(sparse):
    row_coo, col_coo, val_coo, row_count, col_count = sparse_to_coo(sparse)
    RCV = sorted(zip(row_coo, col_coo, val_coo))
    
    
    col_csr = [c for _, c, _ in RCV]
    val_csr = [v for _, _, v in RCV]
    row_csr = [0]
    last_row_processed = 0
    
    for index, rcv in enumerate(RCV):
        if rcv[0] != last_row_processed:
            row_csr.append(index)
            last_row_processed = rcv[0]

    row_csr = row_csr + [len(val_csr)] # todo
        

    return row_csr, col_csr, val_csr, row_count, col_count


row_csr, col_csr, val_csr, row_count, col_count = sparse_to_csr(sparse)  


print("row_csr:", row_csr, "\n")
print("col_csr:", col_csr, "\n")
print("val_csr:", val_csr, "\n")
print("row_count:", row_count, "\n")
print("col_count:", col_count, "\n")
print("storage:", len(row_csr) + len(col_csr) + len(val_csr) + 1 + 1, "\n")

row_csr: [0, 7, 13, 18, 23, 28, 33, 38, 43, 48, 53, 59, 64, 69, 74, 79, 84, 89, 94, 99, 105, 110, 115, 120, 125, 130, 135, 140, 145, 151] 

col_csr: [0, 2, 7, 9, 11, 16, 21, 1, 3, 9, 11, 16, 21, 2, 9, 11, 16, 21, 1, 9, 11, 16, 21, 8, 9, 11, 16, 21, 3, 9, 11, 16, 21, 7, 9, 11, 16, 21, 5, 9, 11, 16, 21, 1, 9, 11, 16, 21, 2, 9, 11, 16, 21, 4, 6, 9, 11, 16, 21, 2, 9, 11, 16, 21, 1, 9, 11, 16, 21, 8, 9, 11, 16, 21, 3, 9, 11, 16, 21, 7, 9, 11, 16, 21, 5, 9, 11, 16, 21, 1, 9, 11, 16, 21, 2, 9, 11, 16, 21, 4, 6, 9, 11, 16, 21, 2, 9, 11, 16, 21, 1, 9, 11, 16, 21, 8, 9, 11, 16, 21, 3, 9, 11, 16, 21, 7, 9, 11, 16, 21, 5, 9, 11, 16, 21, 1, 9, 11, 16, 21, 2, 9, 11, 16, 21, 4, 6, 9, 11, 16, 21] 

val_csr: [1, 5, 9, 1, 5, 9, 9, 2, 3, 1, 5, 9, 9, 3, 1, 5, 9, 9, 4, 1, 5, 9, 9, 1, 1, 5, 9, 9, 8, 1, 5, 9, 9, 2, 1, 5, 9, 9, 9, 1, 5, 9, 9, 8, 1, 5, 9, 9, 3, 1, 5, 9, 9, 2, 1, 1, 5, 9, 9, 3, 1, 5, 9, 9, 4, 1, 5, 9, 9, 1, 1, 5, 9, 9, 8, 1, 5, 9, 9, 2, 1, 5, 9, 9, 9, 1, 5, 9, 9, 8, 1, 5, 9, 9, 3, 1, 5, 9, 9, 2

### Convert CSR Format to Matrix

In [20]:
def csr_to_matrix(row_csr, col_csr, val_csr, row_count, col_count):
    matrix = np.zeros((row_count, col_count), dtype=int)

    for row in range(len(row_csr) - 1):
        start = row_csr[row]
        stop = row_csr[row + 1]
        
        for col_ind in range(start, stop):
            matrix[row, col_csr[col_ind]] = val_csr[col_ind]
    return matrix


csr_result = csr_to_matrix(row_csr, col_csr, val_csr, row_count, col_count)  
csr_result

array([[1, 0, 5, 0, 0, 0, 0, 9, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 2, 0, 3, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 0, 8, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 9, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 9, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0,

In [18]:
np.testing.assert_equal(csr_result, sparse)

### Notes
- CSR and COO are same complexity when there is only one item per row. 
- CSR and CSC are very similar, I could make a generic method for either